parameters:
  queueName: ''
  queueVm: ''
  beforeBuild: []
  afterBuild: []
  afterRestore: []
  beforeTest: []
  customBuild: []
  afterTest: []
  variables:
  publishTasks: []
  persistCredentials: false
  testsEnabled: true
  coverageEnabled: true
  coverageDirectory: ''
  netsdk: '8.0.101'
  nodejs: '17.9.x'
  python: '3.6'
  
#resources:
#- repositories: self

jobs:
- job: Build
  
  pool:
      name: ${{ parameters.queueName }}
      vmImage: ${{ parameters.queueVm }}
  variables:
    ${{ insert }}: ${{ parameters.variables }}
  
  steps:
  - checkout: self
    clean: true
    persistCredentials: ${{ parameters.persistCredentials }}

  - ${{ parameters.beforeBuild }}

  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk ${{ parameters.netsdk }}'
    inputs:
      packageType: sdk
      version: ${{ parameters.netsdk }}

  - task: NodeTool@0
    displayName: 'Use NodeJS ${{ parameters.nodejs }}'
    inputs:
      versionSpec: ${{ parameters.nodejs }}

  - task: UsePythonVersion@0
    displayName: 'Use Python ${{ parameters.python }}'
    inputs:
      versionSpec: ${{ parameters.python }}
    condition: false
  
  - task: DotNetCoreCLI@2
    displayName: Restore local tools
    enabled: false
    inputs:
      command: custom
      custom: tool
      arguments: restore

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore
      projects: '$(RestoreBuildProjects)'
      #feedsToUse: config
      #nugetConfigPath: $(System.DefaultWorkingDirectory)/nuget.config

  - ${{ parameters.afterRestore }}
  
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects: '$(RestoreBuildProjects)'
      arguments: '--configuration $(BuildConfiguration)'

  - ${{ parameters.customBuild }}
  
  - task: DotNetCoreCLI@2
    displayName: Test
    enabled: ${{ parameters.testsEnabled }}
    inputs:
      command: test
      projects: '$(TestProjects)'
      arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura ${{ parameters.additionalTestArguments }}' 

  - ${{ parameters.afterTest }}

  - task: DotNetCoreCLI@2
    displayName: Generate PR Coverage Report
    enabled: ${{ parameters.coverageEnabled }}
    inputs:
      command: custom
      custom: reportgenerator
      arguments: '-reports:../../**/coverage.cobertura.xml -reports:../../**/cobertura-coverage.xml -targetdir:../../coverage -reporttypes:Cobertura'
      workingDirectory: ${{ parameters.coverageDirectory }}
    condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false), in(variables['Build.Reason'], 'PullRequest', 'CheckInShelveset')) 

  - task: DotNetCoreCLI@2
    displayName: Generate Full Coverage Report
    enabled: ${{ parameters.coverageEnabled }}
    inputs:
      command: custom
      custom: reportgenerator
      arguments: '-reports:../../**/coverage.cobertura.xml -reports:../../**/cobertura-coverage.xml -targetdir:../../coverage -reporttypes:HTMLInline;Cobertura'
      workingDirectory: ${{ parameters.coverageDirectory }}
    condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false), notIn(variables['Build.Reason'], 'PullRequest', 'CheckInShelveset')) 
      
  - task: PublishCodeCoverageResults@1
    displayName: Publish coverage
    enabled: ${{ parameters.coverageEnabled }}
    inputs:
      codeCoverageTool: cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/Cobertura.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/coverage/'
  
  - ${{ parameters.publishTasks }}
    
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
    condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false), notIn(variables['Build.Reason'], 'PullRequest', 'CheckInShelveset')) 
      
  - ${{ parameters.afterBuild }}
