//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace СертификацияСемян {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Глобальные {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Глобальные() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("СертификацияСемян.Глобальные", typeof(Глобальные).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Назад {
            get {
                return ResourceManager.GetString("Назад", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeds Certification.
        /// </summary>
        public static string НазваниеПриложения {
            get {
                return ResourceManager.GetString("НазваниеПриложения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field {0} is required.
        /// </summary>
        public static string ОбязательноеПоле {
            get {
                return ResourceManager.GetString("ОбязательноеПоле", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Одобрить {
            get {
                return ResourceManager.GetString("Одобрить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Отклонить {
            get {
                return ResourceManager.GetString("Отклонить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Поиск {
            get {
                return ResourceManager.GetString("Поиск", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to completely delete the record?.
        /// </summary>
        public static string ПредупреждениеПроУдаление {
            get {
                return ResourceManager.GetString("ПредупреждениеПроУдаление", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Редактировать {
            get {
                return ResourceManager.GetString("Редактировать", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Сохранить {
            get {
                return ResourceManager.GetString("Сохранить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planned.
        /// </summary>
        public static string СтатусИнспекции_Запланирована {
            get {
                return ResourceManager.GetString("СтатусИнспекции_Запланирована", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string СтатусИнспекции_Одобрена {
            get {
                return ResourceManager.GetString("СтатусИнспекции_Одобрена", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string СтатусИнспекции_Отклонена {
            get {
                return ResourceManager.GetString("СтатусИнспекции_Отклонена", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string СтатусИнспекции_Проведена {
            get {
                return ResourceManager.GetString("СтатусИнспекции_Проведена", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Страница_Документы {
            get {
                return ResourceManager.GetString("Страница_Документы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Страница_Контакты {
            get {
                return ResourceManager.GetString("Страница_Контакты", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Страница_ОНас {
            get {
                return ResourceManager.GetString("Страница_ОНас", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot.
        /// </summary>
        public static string ТипИнспекции_Партии {
            get {
                return ResourceManager.GetString("ТипИнспекции_Партии", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final.
        /// </summary>
        public static string ТипИнспекции_Поcлеуборочная {
            get {
                return ResourceManager.GetString("ТипИнспекции_Поcлеуборочная", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string ТипИнспекции_Полевая {
            get {
                return ResourceManager.GetString("ТипИнспекции_Полевая", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potato.
        /// </summary>
        public static string ТипСертификата_Картофель {
            get {
                return ResourceManager.GetString("ТипСертификата_Картофель", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Удалить {
            get {
                return ResourceManager.GetString("Удалить", resourceCulture);
            }
        }
    }
}
