//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace СертификацияСемян.Areas.Identity.Pages.Account.Manage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Manage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Manage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("СертификацияСемян.Areas.Identity.Pages.Account.Manage.Manage", typeof(Manage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        internal static string Аккаунт {
            get {
                return ResourceManager.GetString("Аккаунт", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should.
        /// </summary>
        internal static string ВамСледует {
            get {
                return ResourceManager.GetString("ВамСледует", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account contains personal data that you have given us. This page allows you to download or delete that data..
        /// </summary>
        internal static string ВашАккаунтСодержит {
            get {
                return ResourceManager.GetString("ВашАккаунтСодержит", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to into your two factor authenticator app. Spaces and casing do not matter..
        /// </summary>
        internal static string ВВашАутентификатор {
            get {
                return ResourceManager.GetString("ВВашАутентификатор", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the code..
        /// </summary>
        internal static string ВведитеКод {
            get {
                return ResourceManager.GetString("ВведитеКод", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter new email..
        /// </summary>
        internal static string ВведитеНовуюПочту {
            get {
                return ResourceManager.GetString("ВведитеНовуюПочту", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password..
        /// </summary>
        internal static string ВведитеПароль {
            get {
                return ResourceManager.GetString("ВведитеПароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email..
        /// </summary>
        internal static string ВведитеПочту {
            get {
                return ResourceManager.GetString("ВведитеПочту", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable QR code generation.
        /// </summary>
        internal static string ВключитьГенерацию {
            get {
                return ResourceManager.GetString("ВключитьГенерацию", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External logins.
        /// </summary>
        internal static string ВнешниеВходы {
            get {
                return ResourceManager.GetString("ВнешниеВходы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your.
        /// </summary>
        internal static string ВойдитеИспользуя {
            get {
                return ResourceManager.GetString("ВойдитеИспользуя", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before you can log in with a recovery code..
        /// </summary>
        internal static string ВойтиСКодами {
            get {
                return ResourceManager.GetString("ВойтиСКодами", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must.
        /// </summary>
        internal static string ВыДолжны {
            get {
                return ResourceManager.GetString("ВыДолжны", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the policy before you can enable two factor authentication..
        /// </summary>
        internal static string ВыДолжныПринять {
            get {
                return ResourceManager.GetString("ВыДолжныПринять", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can.
        /// </summary>
        internal static string ВыМожете {
            get {
                return ResourceManager.GetString("ВыМожете", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating new recovery codes does not change the keys used in authenticator apps. If you wish to change the key
        ///used in an authenticator app you should.
        /// </summary>
        internal static string ГенерацияНовыхКодовНеМеняет {
            get {
                return ResourceManager.GetString("ГенерацияНовыхКодовНеМеняет", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Recovery Codes.
        /// </summary>
        internal static string ГенерироватьКоды {
            get {
                return ResourceManager.GetString("ГенерироватьКоды", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Authenticator for.
        /// </summary>
        internal static string ГуглАутентификатор {
            get {
                return ResourceManager.GetString("ГуглАутентификатор", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication.
        /// </summary>
        internal static string ДвухФакторнаяАутентификация {
            get {
                return ResourceManager.GetString("ДвухФакторнаяАутентификация", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action only disables 2FA..
        /// </summary>
        internal static string ДействиеОтключаетАутентификацию {
            get {
                return ResourceManager.GetString("ДействиеОтключаетАутентификацию", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another service to log in..
        /// </summary>
        internal static string ДобавитьДругойСервис {
            get {
                return ResourceManager.GetString("ДобавитьДругойСервис", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add authenticator app.
        /// </summary>
        internal static string ДобавитьПриложение {
            get {
                return ResourceManager.GetString("ДобавитьПриложение", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you reset your authenticator key your authenticator app will not work until you reconfigure it..
        /// </summary>
        internal static string ЕслиОбнулитеКлюч {
            get {
                return ResourceManager.GetString("ЕслиОбнулитеКлюч", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you lose your device and don&apos;t have the recovery codes you will lose access to your account..
        /// </summary>
        internal static string ЕслиПотеряетеКоды {
            get {
                return ResourceManager.GetString("ЕслиПотеряетеКоды", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget this browser.
        /// </summary>
        internal static string ЗабытьБраузер {
            get {
                return ResourceManager.GetString("ЗабытьБраузер", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download a two-factor authenticator app like Microsoft Authenticator for.
        /// </summary>
        internal static string ЗагрузитеАутентификатор {
            get {
                return ResourceManager.GetString("ЗагрузитеАутентификатор", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Your Data.
        /// </summary>
        internal static string ЗагрузитеДанные {
            get {
                return ResourceManager.GetString("ЗагрузитеДанные", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Загрузить {
            get {
                return ResourceManager.GetString("Загрузить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Закрыть {
            get {
                return ResourceManager.GetString("Закрыть", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Logins.
        /// </summary>
        internal static string ЗарегистрированныеВходы {
            get {
                return ResourceManager.GetString("ЗарегистрированныеВходы", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string И {
            get {
                return ResourceManager.GetString("И", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ИзменитьПароль {
            get {
                return ResourceManager.GetString("ИзменитьПароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email.
        /// </summary>
        internal static string ИзменитьПочту {
            get {
                return ResourceManager.GetString("ИзменитьПочту", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        internal static string Или {
            get {
                return ResourceManager.GetString("Или", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to recovery codes left..
        /// </summary>
        internal static string КодовОсталось {
            get {
                return ResourceManager.GetString("КодовОсталось", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification Code.
        /// </summary>
        internal static string КодПодтверждения {
            get {
                return ResourceManager.GetString("КодПодтверждения", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery codes.
        /// </summary>
        internal static string КодыВосстановления {
            get {
                return ResourceManager.GetString("КодыВосстановления", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal data.
        /// </summary>
        internal static string ЛичныеДанные {
            get {
                return ResourceManager.GetString("ЛичныеДанные", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login from your account.
        /// </summary>
        internal static string ЛогинИзАккаунта {
            get {
                return ResourceManager.GetString("ЛогинИзАккаунта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure authenticator app.
        /// </summary>
        internal static string НастроитьАутентификатор {
            get {
                return ResourceManager.GetString("НастроитьАутентификатор", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn how to.
        /// </summary>
        internal static string Научитесь {
            get {
                return ResourceManager.GetString("Научитесь", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no recovery codes left..
        /// </summary>
        internal static string НеОсталосьКодов {
            get {
                return ResourceManager.GetString("НеОсталосьКодов", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a local username/password for this site. Add a local
        ///account so you can log in without an external login..
        /// </summary>
        internal static string НетЛокальногоАккаунта {
            get {
                return ResourceManager.GetString("НетЛокальногоАккаунта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your new password..
        /// </summary>
        internal static string НовыйПароль {
            get {
                return ResourceManager.GetString("НовыйПароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update password.
        /// </summary>
        internal static string ОбновитьПароль {
            get {
                return ResourceManager.GetString("ОбновитьПароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset your authenticator keys..
        /// </summary>
        internal static string ОбнулитеКлючи {
            get {
                return ResourceManager.GetString("ОбнулитеКлючи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator key.
        /// </summary>
        internal static string ОбнулитьКлюч {
            get {
                return ResourceManager.GetString("ОбнулитьКлюч", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset recovery codes.
        /// </summary>
        internal static string ОбнулитьКоды {
            get {
                return ResourceManager.GetString("ОбнулитьКоды", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset authenticator app.
        /// </summary>
        internal static string ОбнулитьПриложение {
            get {
                return ResourceManager.GetString("ОбнулитьПриложение", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have 1 recovery code left..
        /// </summary>
        internal static string ОдинКод {
            get {
                return ResourceManager.GetString("ОдинКод", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once you have scanned the QR code or input the key above, your two factor authentication app will provide you
        ///with a unique code. Enter the code in the confirmation box below..
        /// </summary>
        internal static string ОднаждыОтсканировав {
            get {
                return ResourceManager.GetString("ОднаждыОтсканировав", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabling 2FA does not change the keys used in authenticator apps. If you wish to change the key used in an authenticator app you should.
        /// </summary>
        internal static string ОтключениеНеМеняетКлючи {
            get {
                return ResourceManager.GetString("ОтключениеНеМеняетКлючи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable 2FA.
        /// </summary>
        internal static string Отключить2ФА {
            get {
                return ResourceManager.GetString("Отключить2ФА", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable two-factor authentication (2FA).
        /// </summary>
        internal static string ОтключитьАутентификацию {
            get {
                return ResourceManager.GetString("ОтключитьАутентификацию", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan the QR Code or enter this key.
        /// </summary>
        internal static string ОтсканируйтеКР {
            get {
                return ResourceManager.GetString("ОтсканируйтеКР", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Пароль {
            get {
                return ResourceManager.GetString("Пароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reset your authenticator keys..
        /// </summary>
        internal static string ПереустановитьКлючи {
            get {
                return ResourceManager.GetString("ПереустановитьКлючи", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your new password..
        /// </summary>
        internal static string ПодтвердитеПароль {
            get {
                return ResourceManager.GetString("ПодтвердитеПароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string Подтвердить {
            get {
                return ResourceManager.GetString("Подтвердить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy and cookie policy have not been accepted..
        /// </summary>
        internal static string ПолитикаНеПринята {
            get {
                return ResourceManager.GetString("ПолитикаНеПринята", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        internal static string ПоменяйтеНастройкиАккаунта {
            get {
                return ResourceManager.GetString("ПоменяйтеНастройкиАккаунта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send verification email.
        /// </summary>
        internal static string ПослатьПодтверждение {
            get {
                return ResourceManager.GetString("ПослатьПодтверждение", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Почта {
            get {
                return ResourceManager.GetString("Почта", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Профиль {
            get {
                return ResourceManager.GetString("Профиль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This process disables 2FA until you verify your authenticator app.
        ///If you do not complete your authenticator app configuration you may lose access to your account..
        /// </summary>
        internal static string ПроцессОтключает2ФА {
            get {
                return ResourceManager.GetString("ПроцессОтключает2ФА", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate two-factor authentication (2FA) recovery codes.
        /// </summary>
        internal static string Сгенерировать2ФАКоды {
            get {
                return ResourceManager.GetString("Сгенерировать2ФАКоды", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generate a new set of recovery codes.
        /// </summary>
        internal static string СгенерируйтеНовыеКоды {
            get {
                return ResourceManager.GetString("СгенерируйтеНовыеКоды", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put these codes in a safe place..
        /// </summary>
        internal static string СохранитеКоды {
            get {
                return ResourceManager.GetString("СохранитеКоды", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your old password..
        /// </summary>
        internal static string СтарыйПароль {
            get {
                return ResourceManager.GetString("СтарыйПароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this.
        /// </summary>
        internal static string УберитеЭтот {
            get {
                return ResourceManager.GetString("УберитеЭтот", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Убрать {
            get {
                return ResourceManager.GetString("Убрать", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have.
        /// </summary>
        internal static string УВасЕсть {
            get {
                return ResourceManager.GetString("УВасЕсть", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this data will permanently remove your account, and this cannot be recovered..
        /// </summary>
        internal static string УдалениеПриведет {
            get {
                return ResourceManager.GetString("УдалениеПриведет", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this data will permanently remove your account, and this cannot be recovered..
        /// </summary>
        internal static string УдалениеЭтихДанных {
            get {
                return ResourceManager.GetString("УдалениеЭтихДанных", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Удалить {
            get {
                return ResourceManager.GetString("Удалить", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete data and close my account.
        /// </summary>
        internal static string УдалитьИЗакрыть {
            get {
                return ResourceManager.GetString("УдалитьИЗакрыть", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete personal password.
        /// </summary>
        internal static string УдалитьЛичныеДанные {
            get {
                return ResourceManager.GetString("УдалитьЛичныеДанные", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your account.
        /// </summary>
        internal static string УправляйтеАккаунтом {
            get {
                return ResourceManager.GetString("УправляйтеАккаунтом", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your external logins.
        /// </summary>
        internal static string УправлятьВнешнимиЛогинами {
            get {
                return ResourceManager.GetString("УправлятьВнешнимиЛогинами", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Email.
        /// </summary>
        internal static string УправлятьПочтой {
            get {
                return ResourceManager.GetString("УправлятьПочтой", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set your password.
        /// </summary>
        internal static string УстановитеВашПароль {
            get {
                return ResourceManager.GetString("УстановитеВашПароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        internal static string УстановитьПароль {
            get {
                return ResourceManager.GetString("УстановитьПароль", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up authenticator app.
        /// </summary>
        internal static string УстановитьПриложение {
            get {
                return ResourceManager.GetString("УстановитьПриложение", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use an authenticator app go through the following steps:.
        /// </summary>
        internal static string ЧтобыИспользоватьАутентификатор {
            get {
                return ResourceManager.GetString("ЧтобыИспользоватьАутентификатор", resourceCulture);
            }
        }
    }
}
